name: Auto Assign to Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    name: Add issue or PR to GitHub Project
    runs-on: ubuntu-latest
    steps:
      - name: Add to Project
        uses: actions/add-to-project@v1.0.1
        with:
          # A URL do projeto que você vai criar no GitHub. Substitua o link abaixo pelo seu!
          project-url: https://github.com/users/thinkmadu/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
